from django.db import models
h_types = ((1,'low'),(2,'medium'),(3,'high'))
p_types = ((1,'absent'),(2,'present'))
income_types = ((1,'no income'),(2,'less than 1000 yuan'),(3,'beteen 1000 to 1999 yuan'),(4,'between 2000 to 3499'),(5,'more than 3500'))
ofend_types = ()
class Recidivism(models.Model):
    age = models.IntegerField()
    education = models.IntegerField()
    monthly_family_income = models.IntegerField(choices=income_types)
    offender = models.IntegerField()
    History_of_violence  = models.IntegerField(choices=h_types)
    History_of_non_violent_offending  = models.IntegerField(choices=h_types)
    Early_initiation_of_violence  = models.IntegerField(choices=h_types)
    Past_supervision = models.IntegerField(choices=h_types)
    History_of_self_harm_or_suicide_attempts = models.IntegerField(choices=h_types)
    Exposure_to_violence_in_the_home = models.IntegerField(choices=h_types)
    Childhood_history_of_maltreatment  = models.IntegerField(choices=h_types)
    Parental_or_caregiver_criminality  = models.IntegerField(choices=h_types)
    Early_caregiver_disruption = models.IntegerField(choices=h_types)
    Poor_school_achievement = models.IntegerField(choices=h_types)
    Peer_delinquency  = models.IntegerField(choices=h_types)
    Peer_rejection  = models.IntegerField(choices=h_types)
    Stress_and_poor_coping = models.IntegerField(choices=h_types)
    Poor_parental_management = models.IntegerField(choices=h_types)
    Lack_of_personal_or_social_support  = models.IntegerField(choices=h_types)
    Community_disorganization = models.IntegerField(choices=h_types)
    Negative_attitudes = models.IntegerField(choices=h_types)
    Risk_taking_or_Impulsivity = models.IntegerField(choices=h_types)
    Substance_use_difficulties  = models.IntegerField(choices=h_types)
    Anger_management_problems = models.IntegerField(choices=h_types)
    Psychopathic_traits  = models.IntegerField(choices=h_types)
    Attention_deficit_or_hyperactivity_difficulties  = models.IntegerField(choices=h_types)
    Poor_compliance = models.IntegerField(choices=h_types)
    Low_interest_or_Commitment_or_to_school = models.IntegerField(choices=h_types)
    Prosocial_involvement  = models.IntegerField(choices=p_types)
    Strong_social_support  = models.IntegerField(choices=p_types)
    Strong_attachment_and_bonds  = models.IntegerField(choices=p_types)
    Positive_attitude_toward_intervention_and_authority = models.IntegerField(choices=p_types)
    Strong_commitment_to_school  = models.IntegerField(choices=p_types)
    Resilient_personality_traits = models.IntegerField(choices=p_types)

