# Generated by Django 4.2.2 on 2023-06-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recidivism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('education', models.IntegerField()),
                ('monthly_family_income', models.IntegerField(choices=[('no income', 1), ('less than 1000 yuan', 2), ('beteen 1000 to 1999 yuan', 3), ('between 2000 to 3499', 4), ('more than 3500', 5)])),
                ('offender', models.IntegerField()),
                ('History_of_violence', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('History_of_non_violent_offending', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Early_initiation_of_violence', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Past_supervision', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('History_of_self_harm_or_suicide_attempts', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Exposure_to_violence_in_the_home', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Childhood_history_of_maltreatment', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Parental_or_caregiver_criminality', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Early_caregiver_disruption', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Poor_school_achievement', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Peer_delinquency', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Peer_rejection', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Stress_and_poor_coping', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Poor_parental_management', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Lack_of_personal_or_social_support', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Community_disorganization', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Negative_attitudes', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Risk_taking_or_Impulsivity', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Substance_use_difficulties', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Anger_management_problems', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Psychopathic_traits', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Attention_deficit_or_hyperactivity_difficulties', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Poor_compliance', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Low_interest_or_Commitment_or_to_school', models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)])),
                ('Prosocial_involvement', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
                ('Strong_social_support', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
                ('Strong_attachment_and_bonds', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
                ('Positive_attitude_toward_intervention_and_authority', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
                ('Strong_commitment_to_school', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
                ('Resilient_personality_traits', models.IntegerField(choices=[('absent', 1), ('present', 2)])),
            ],
        ),
    ]
